title: Adam Fraser # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a business intelligence analyst with Employment and Social Development Canada. I perform a variety of data analysis techniques to discover insights in how to improve government programs.   
  <br><br>
  I have degrees in Cognitive Science and Neuroscience ... machine learning 
  <br><br>
  <a href="https://www.linkedin.com/in/adam-fraser-212732126/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
