title: Adam Fraser # your name (or website title) here
logo: "/images/logo2.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a business intelligence analyst dedicated to finding data-driven solutions to improve government programs and business operations.   
  <br><br>
  I developed my passion and expertise for data analysis through my studies in Cognitive Science and Neuroscience. My research focused on problems that relied on implementing modern data science techniques, such as machine learning to establish predictive models to detect mental fatigue. 
  <br><br>
  Ottawa, Ontario, Canada<br><br>akfraser96@gmail.com
  <br><br>
  <a href="https://www.linkedin.com/in/adam-fraser-212732126/">View My LinkedIn Profile</a> 
  
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
