title: Adam Fraser # your name (or website title) here
logo: "/images/logo4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <p style='color&#x3a;#000000!important'>Currently working as a data analyst with the Canadian federal government.
  <br><br>
  I am motivated by making engaging data science products such as web applications and automated dashboards.  
  <br><br>
  Kingston, Ontario, Canada</p>
  <br><br>
  <a href="mailto:akfraser96@gmail.com">akfraser96@gmail.com</a> 
  <br><br>
  
theme: jekyll-theme-minimal

