title: Adam Fraser # your name (or website title) here
logo: "/images/logo4.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <style='color:black!important'>I am a business intelligence data analyst currently working with the Canadian federal government.
  <br>
  I developed my passion and expertise for data science through my studies in neuroscience and psychology. My research focused on applying machine learning to solve real-world psychology problems, such as detecting onset of fatigue and mental overload. 
  <br><br>
  Kingston, Ontario, Canada
  <br><br>
  <a href="mailto:akfraser96@gmail.com">akfraser96@gmail.com</a> 
  <br><br>
  </style>
theme: styles.css

